# Generated by Django 3.1.3 on 2020-12-01 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket_app', '0002_auto_20201201_1728'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vendor',
            table='vendor',
        ),
    ]
