# Generated by Django 3.1.3 on 2020-12-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket_app', '0003_auto_20201201_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='phone_no',
            field=models.CharField(max_length=10),
        ),
    ]
