# Generated by Django 3.1.3 on 2020-12-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket_app', '0004_auto_20201204_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='company_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='location',
            field=models.CharField(max_length=50),
        ),
    ]
