# Generated by Django 3.1.3 on 2020-12-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket_app', '0005_auto_20201204_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('mgr_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mgr_name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
            ],
            options={
                'db_table': 'Manager',
            },
        ),
    ]
