# Generated by Django 3.1.3 on 2020-12-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket_app', '0008_auto_20201208_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
