# Generated by Django 3.1.3 on 2020-12-24 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket_app', '0009_auto_20201218_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('stock_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sec_name', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(max_length=10)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket_app.items')),
            ],
            options={
                'db_table': 'Stocks',
            },
        ),
    ]
