# Generated by Django 3.1.3 on 2020-12-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket_app', '0010_stocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
