# Generated by Django 3.1.3 on 2020-12-25 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket_app', '0011_auto_20201225_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocks',
            old_name='item_id',
            new_name='item',
        ),
    ]
